"""generate_robots_patch — pure-rule robots.txt generator for AI bot access.

No LLM call. Fetches existing robots.txt via _fetch (SSRF-guarded), strips
out any existing AI-bot rules, re-generates them from the canonical bot registry,
and returns a ready-to-paste new robots.txt + unified diff.
"""

from __future__ import annotations

import difflib
from datetime import date
from typing import Any, List, Optional

from ..bots import KNOWN_AI_BOTS
from ..robots import normalize_domain

_AI_BOT_UAS_LOWER: frozenset[str] = frozenset(b.ua.lower() for b in KNOWN_AI_BOTS)


def _extract_non_ai_lines(robots_text: str) -> list[str]:
    """Return lines from robots_text that don't belong to known AI bot UA blocks."""
    lines = robots_text.splitlines()
    result: list[str] = []
    i = 0

    while i < len(lines):
        raw = lines[i]

        if raw.strip().lower().startswith("user-agent:"):
            # Collect consecutive user-agent lines for this block
            block_start = i
            uas: list[str] = []
            while i < len(lines) and lines[i].strip().lower().startswith("user-agent:"):
                _, _, val = lines[i].partition(":")
                uas.append(val.strip())
                i += 1

            # Collect rule lines until blank line or next user-agent
            rule_end = i
            while rule_end < len(lines):
                s = lines[rule_end].strip()
                if not s or s.lower().startswith("user-agent:"):
                    break
                rule_end += 1

            if any(ua.lower() in _AI_BOT_UAS_LOWER for ua in uas):
                # Skip entire AI bot block — we'll re-generate it
                i = rule_end
            else:
                result.extend(lines[block_start:rule_end])
                i = rule_end
        else:
            result.append(raw)
            i += 1

    # Strip trailing blank lines
    while result and not result[-1].strip():
        result.pop()

    return result


async def generate_robots_patch(
    domain: str,
    *,
    allow_bots: Optional[List[str]] = None,
    deny_bots: Optional[List[str]] = None,
    preserve_existing: bool = True,
) -> dict[str, Any]:
    """Generate a corrected robots.txt that opens access to AI bots.

    Fetches the existing robots.txt (SSRF-guarded), strips existing AI bot
    rules, and re-generates them from the canonical 22-bot registry. Pure
    rule generation — no LLM call.

    Args:
        domain: e.g. ``example.com`` or ``https://example.com``
        allow_bots: UA tokens to allow. ``None`` = all 22 known AI bots.
        deny_bots: UA tokens to explicitly disallow. Takes priority over allow_bots.
        preserve_existing: if True, preserve non-AI-bot rules from existing robots.txt.

    Returns:
        dict with keys: domain, existing_robots, new_robots, diff,
        bots_allowed, bots_denied, cloudflare_warning, paste_target.
        On SSRF error returns dict with ``error`` key.
    """
    # Lazy import to avoid circular: server imports generators, generators import server
    from ..server import SSRFBlocked, _fetch

    import httpx

    base = normalize_domain(domain)
    robots_url = f"{base}/robots.txt"

    existing_text: str | None = None
    cloudflare_warning: str | None = None

    try:
        status, headers, body = await _fetch(robots_url)
        if status == 200:
            existing_text = body

        h = {k.lower(): v for k, v in headers.items()}
        if "cloudflare" in h.get("server", "").lower() or "cf-ray" in h:
            cloudflare_warning = (
                "robots.txt change alone won't bypass Cloudflare AI bot challenge — "
                "also disable 'AI Scrapers and Crawlers' in Cloudflare WAF Bot Management."
            )
    except SSRFBlocked as exc:
        return {"domain": base, "error": f"refused: {exc}"}
    except httpx.HTTPError:
        # Network failure: treat as missing robots.txt, continue
        existing_text = None

    # Resolve effective allow/deny lists
    all_ai_uas = [b.ua for b in KNOWN_AI_BOTS]
    effective_allow: list[str] = list(allow_bots) if allow_bots is not None else all_ai_uas
    effective_deny: list[str] = list(deny_bots) if deny_bots is not None else []

    deny_set = set(effective_deny)
    effective_allow = [ua for ua in effective_allow if ua not in deny_set]

    # Build new robots.txt
    lines: list[str] = []

    if preserve_existing and existing_text:
        non_ai = _extract_non_ai_lines(existing_text)
        lines.extend(non_ai)
        if lines and lines[-1].strip():
            lines.append("")  # blank separator before AI section

    today = date.today().isoformat()
    lines.append(f"# AI bots — generated by ai-visibility-mcp {today}")

    for ua in effective_allow:
        lines.append(f"User-agent: {ua}")
        lines.append("Allow: /")
        lines.append("")

    for ua in effective_deny:
        lines.append(f"User-agent: {ua}")
        lines.append("Disallow: /")
        lines.append("")

    new_robots = "\n".join(lines)
    if not new_robots.endswith("\n"):
        new_robots += "\n"

    existing_for_diff = existing_text or ""
    diff = "".join(
        difflib.unified_diff(
            existing_for_diff.splitlines(keepends=True),
            new_robots.splitlines(keepends=True),
            fromfile="robots.txt (existing)",
            tofile="robots.txt (new)",
        )
    )

    return {
        "domain": base,
        "existing_robots": existing_text,
        "new_robots": new_robots,
        "diff": diff,
        "bots_allowed": effective_allow,
        "bots_denied": effective_deny,
        "cloudflare_warning": cloudflare_warning,
        "paste_target": "/robots.txt at site root, replaces existing",
    }
